# Generated by Django 4.2.27 on 2026-04-02 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('ecocash', 'EcoCash')], default='cash', max_length=20),
        ),
    ]
