# Generated by Django 4.2.27 on 2026-04-06 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_product_client_transaction_client_alter_product_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='buying_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='transactionitem',
            name='line_profit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='transactionitem',
            name='unit_buying_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
