# Generated by Django 4.2.27 on 2026-04-06 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_product_buying_price_transactionitem_line_profit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientbusiness',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
