from django.contrib.auth.views import LogoutView
from django.urls import path

from .views import (
    UserLoginView,
    backup_database,
    changes_list,
    client_create,
    client_delete,
    client_add_cashier,
    client_toggle_active,
    client_update,
    complete_sale,
    dashboard,
    account_deactivated,
    force_change_password,
    home_redirect,
    new_sale,
    no_access,
    product_create,
    product_delete,
    product_list,
    product_update,
    remove_sale_item,
    sysadmin_dashboard,
    transaction_list,
)

urlpatterns = [
    path('', home_redirect, name='home'),
    path('no-access/', no_access, name='no_access'),
    path('account-deactivated/', account_deactivated, name='account_deactivated'),
    path('login/', UserLoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('force-change-password/', force_change_password, name='force_change_password'),
    path('system-admin/', sysadmin_dashboard, name='sysadmin_dashboard'),
    path('system-admin/clients/new/', client_create, name='client_create'),
    path('system-admin/clients/<int:pk>/edit/', client_update, name='client_update'),
    path('system-admin/clients/<int:pk>/delete/', client_delete, name='client_delete'),
    path('system-admin/clients/<int:pk>/toggle-active/', client_toggle_active, name='client_toggle_active'),
    path('system-admin/clients/<int:pk>/cashiers/new/', client_add_cashier, name='client_add_cashier'),
    path('dashboard/', dashboard, name='dashboard'),
    path('products/', product_list, name='product_list'),
    path('products/new/', product_create, name='product_create'),
    path('products/<int:pk>/edit/', product_update, name='product_update'),
    path('products/<int:pk>/delete/', product_delete, name='product_delete'),
    path('sales/new/', new_sale, name='new_sale'),
    path('sales/remove/<int:product_id>/', remove_sale_item, name='remove_sale_item'),
    path('sales/complete/', complete_sale, name='complete_sale'),
    path('changes/', changes_list, name='changes_list'),
    path('transactions/', transaction_list, name='transaction_list'),
    path('backup/', backup_database, name='backup_database'),
]